### ISSUE TITLE
Waiting for first pageview

### ISSUE THREAD

**Issue by alvarosabu** [nuxt-modules/plausible#2]
Hi there,
I have the module installed, but Im getting this on the dashboard,

Do I need to add the snippet as well? Or is it something that the module should handle?

```
<script defer data-domain="alvarosaburido.dev" src="https://plausible.io/js/script.js"></script>
```

Thanks

<img width="637" alt="Screenshot 2022-11-30 at 20 06 48" src="https://user-images.githubusercontent.com/4699008/204886563-98970900-8e6d-4316-8370-5e1fbefb7355.png">

**Comment by johannschopplich** [comment]
Technically, you don't have to add any configuration when adding the module to your `nuxt.config.ts`.

Have you customized the module's option? And if so, could you please provide its configuration? Does your deployed Nuxt application's domain match the one set up in Plausible?

Otherwise, Plausible may take a while to process the first request. Could you check if it is still missing?

**Comment by alvarosabu** [comment]
Hey, thanks for the quick response, here is my config

```
modules: [
    'nuxt-plausible',
    ...
],
plausible: {
    domain: 'https://alvarosaburido.dev',
 },
```

Yes, the domain is the same on the dashboard. Still the same state as the screenshot

**Comment by johannschopplich** [comment]
You don't need to configure the `domain` module option, it will [default to the `window.location.hostname`](https://github.com/johannschopplich/nuxt-plausible#module-options).

Apart from that, your configuration is malformed. `domain` should be `alvarosaburido.dev` (without protocol).

**Comment by alvarosabu** [comment]
I removed the options, waited a little bit and then started fetching data. Thanks for the support, I'm gonna close this
